import { NextRequest, NextResponse } from "next/server";
import { type CourseLandingPage } from "@/lib/schemas";
import { prisma } from "@/lib/prisma";
import { auth } from "@clerk/nextjs/server";

export async function POST(req: NextRequest) {
    try {
        const { userId } = await auth();

        if (!userId) {
            return NextResponse.json(
                { error: "Unauthorized" },
                { status: 401 }
            );
        }

        const body = (await req.json()) as CourseLandingPage;

        if (!body || !body.hero || !body.hero.headline) {
            console.error("Malformed body received in landing:", body);
            return NextResponse.json(
                { error: "Invalid landing page data" },
                { status: 400 }
            );
        }

        // Generate a unique slug based on the headline
        let baseSlug = body.hero.headline
            .toLowerCase()
            .trim()
            .replace(/[^\w\s-]/g, "")
            .replace(/[\s_-]+/g, "-")
            .substring(0, 40)
            .replace(/^-+|-+$/g, "");

        // Fallback if slug generation fails
        if (!baseSlug) baseSlug = "course";

        // Append a short random string to ensure uniqueness
        const slug = `${baseSlug}-${Math.random().toString(36).substring(2, 7)}`;

        // Ensure pricing is somewhat valid
        const price = typeof body.pricing?.price === "number" ? body.pricing.price : 99.0;

        // Create Course and LandingPage in a transaction
        const course = await prisma.course.create({
            data: {
                title: body.hero.headline,
                userId,
                description: body.hero.subheadline || "A new course generated by AI.",
                price,
                landing: {
                    create: {
                        slug,
                        headline: body.hero.headline,
                        subheadline: body.hero.subheadline || "",
                        sections: body as any, // Storing the full JSON object
                    },
                },
            },
            include: {
                landing: true,
            },
        });


        return NextResponse.json({
            success: true,
            courseId: course.id,
            slug: course.landing?.slug,
            landingPage: course.landing,
        });
    } catch (error: any) {
        console.error("Error saving landing page:", error);
        return NextResponse.json(
            { error: "Internal Server Error", details: error.message },
            { status: 500 }
        );
    }
}
